### ISSUE TITLE
where can i connect to db?

### ISSUE THREAD

**Issue by grandfatheryun** [Cruzoft/nbminer-reporter#4]
can i change something about it?

**Comment by grandfatheryun** [comment]
C:\Users\yun\Desktop\NBMiner_Win>nbreporter -n test -h http://106.53.107.206:8086/
time="2021-11-25T19:44:06+08:00" level=info msg="NBMiner Status Reporter Initiated"
time="2021-11-25T19:44:06+08:00" level=info msg="Using Friendly Name: test"
time="2021-11-25T19:45:06+08:00" level=info msg="Checking Status."
2021/11/25 19:45:09 influxdb2client E! Write error: Post "http://http//106.53.107.206:8086/:8086/api/v2/write?bucket=miner&org=miner-org&precision=ns": dial tcp: lookup http: no such host
Batch kept for retrying
time="2021-11-25T19:45:09+08:00" level=error msg="Something when wrong while trying to send data to InfluxDB."
time="2021-11-25T19:45:09+08:00" level=error msg="Write error: write failed (attempts 1): Post \"http://http//106.53.107.206:8086/:8086/api/v2/write?bucket=miner&org=miner-org&precision=ns\": dial tcp: lookup http: no such host\n"

**Comment by ingcsmoreno** [comment]
the `-h` flag expect just the host, there are separated flags for setting the protocol (http) and port (8086) .

For instance, to connect to http://106.53.107.206:8086, just run it with these params:

```sh
nbreporter -n test -h 106.53.107.206 
```

You won't need to specify the protocol or the port in this case since `http` and `8086` are the default values.

**Comment by ingcsmoreno** [comment]
Also, you can check all the command options [here](https://github.com/Cruzoft/nbminer-reporter#cmd-options). :)

**Comment by grandfatheryun** [comment]
something error:
Error: Failed to create organization: unauthorized access.

**Comment by ingcsmoreno** [comment]
@grandfatheryun Can you try with the setup command:

```bash
influx setup \
      --username miner \
      --password miner-pass \
      --org miner-org \
      --bucket miner \
      --retention 4w \
      -f
```

**Comment by grandfatheryun** [comment]
can it set at gui?

**Comment by ingcsmoreno** [comment]
A UI for InfluxDB? there are other tools for that. You can use [Chronograf](https://www.influxdata.com/time-series-platform/chronograf/) or [Grafana](https://grafana.com/).

I'd recommend `Grafana`, but for a quick test you can use Chronograf with this command:

```bash
docker run --rm --name chronograf -p 8888:8888 chronograf:1.6-alpine --influxdb-url=http://localhost:8086
```

Just change the `localhost` with your InfluxDB host, and it should work, then point your browser to http://localhost:8888.

Also, I'm closing this Issue since the initial connection problem was solved. Feel free to open a new one if you need help with something else.
